version: "3.8"
services:
  backend:
    build:
      context: ./Encuentros-Back
    container_name: encuentros_back
    env_file:
      - ./Encuentros-Back/.env
    environment:
      NODE_ENV: production
      PORT: "3000"
      # Opcional: fuerza DNS estables si Docker hereda resolvers problemáticos
      DNS_SERVERS: "1.1.1.1,8.8.8.8"
    ports:
      - "3000:3000"
    restart: on-failure

  frontend:
    build:
      context: ./Encuentros-Front
    container_name: encuentros_front
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure
