-- Conectar a la PDB
ALTER SESSION SET CONTAINER = XEPDB1;

-- Crear usuario ENCUENTROS_ADMIN
CREATE USER ENCUENTROS_ADMIN IDENTIFIED BY admin DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;

-- Otorgar privilegios básicos necesarios
GRANT CONNECT, RESOURCE, DBA TO ENCUENTROS_ADMIN;

GRANT CREATE SESSION TO ENCUENTROS_ADMIN;

GRANT CREATE TABLE TO ENCUENTROS_ADMIN;

GRANT CREATE VIEW TO ENCUENTROS_ADMIN;

GRANT CREATE SEQUENCE TO ENCUENTROS_ADMIN;

GRANT CREATE PROCEDURE TO ENCUENTROS_ADMIN;

GRANT CREATE TRIGGER TO ENCUENTROS_ADMIN;

GRANT UNLIMITED TABLESPACE TO ENCUENTROS_ADMIN;

-- Desbloquear cuenta
ALTER USER ENCUENTROS_ADMIN ACCOUNT UNLOCK;

EXIT;
