--------------------------------------------------------
--  File created - Sunday-November-09-2025
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_AMISTADES
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_AMISTADES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_APORTES
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_APORTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOLSILLOS
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_BOLSILLOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ENCUENTROS
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_ENCUENTROS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GASTOS
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_GASTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ITEMS_PRESUPUESTO
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_ITEMS_PRESUPUESTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MENSAJES
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_MENSAJES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PARTICIPANTES
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_PARTICIPANTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRESUPUESTOS
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_PRESUPUESTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RECORDATORIOS
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_RECORDATORIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RELACIONES_AMISTADES
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_RELACIONES_AMISTADES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SOLICITUDES_AMISTAD
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_SOLICITUDES_AMISTAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIOS
--------------------------------------------------------

CREATE SEQUENCE  "ENCUENTROS_ADMIN"."SEQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AMISTADES
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."AMISTADES"
   (	"ID_AMISTAD" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_AMISTADES"."NEXTVAL",
	"ID_RELACION_AMISTAD" NUMBER,
	"USUARIO1" NUMBER,
	"USUARIO2" NUMBER,
	"FECHA_AMISTAD" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APORTES
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."APORTES"
   (	"ID_APORTE" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_APORTES"."NEXTVAL",
	"ID_BOLSILLO" NUMBER,
	"ID_ENCUENTRO" NUMBER,
	"ID_USUARIO" NUMBER,
	"MONTO" NUMBER(15,2),
	"FECHA_APORTE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOLSILLOS
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."BOLSILLOS"
   (	"ID_BOLSILLO" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_BOLSILLOS"."NEXTVAL",
	"ID_PRESUPUESTO" NUMBER,
	"ID_ENCUENTRO" NUMBER,
	"NOMBRE" VARCHAR2(200 BYTE),
	"SALDO_ACTUAL" NUMBER(15,2) DEFAULT 0
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENCUENTROS
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."ENCUENTROS"
   (	"ID_ENCUENTRO" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_ENCUENTROS"."NEXTVAL",
	"ID_CREADOR" NUMBER,
	"TITULO" VARCHAR2(200 BYTE),
	"DESCRIPCION" CLOB,
	"LUGAR" VARCHAR2(200 BYTE),
	"FECHA" DATE,
	"FECHA_CREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'en proceso'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("DESCRIPCION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GASTOS
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."GASTOS"
   (	"ID_GASTO" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_GASTOS"."NEXTVAL",
	"ID_BOLSILLO" NUMBER,
	"ID_ENCUENTRO" NUMBER,
	"NOMBRE_ITEM" VARCHAR2(200 BYTE),
	"MONTO" NUMBER(15,2),
	"FECHA_GASTO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEMS_PRESUPUESTO
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO"
   (	"ID_ITEM" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_ITEMS_PRESUPUESTO"."NEXTVAL",
	"ID_PRESUPUESTO" NUMBER,
	"ID_ENCUENTRO" NUMBER,
	"NOMBRE_ITEM" VARCHAR2(200 BYTE),
	"MONTO_ITEM" NUMBER(15,2)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENSAJES
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."MENSAJES"
   (	"ID_MENSAJE" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_MENSAJES"."NEXTVAL",
	"ID_ENCUENTRO" NUMBER,
	"ID_USUARIO" NUMBER,
	"MENSAJE" CLOB,
	"FECHA_ENVIO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("MENSAJE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table PARTICIPANTES_ENCUENTRO
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO"
   (	"ID_PARTICIPACION" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_PARTICIPANTES"."NEXTVAL",
	"ID_ENCUENTRO" NUMBER,
	"ID_USUARIO" NUMBER,
	"ROL" VARCHAR2(20 BYTE) DEFAULT 'Participante'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRESUPUESTOS
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."PRESUPUESTOS"
   (	"ID_PRESUPUESTO" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_PRESUPUESTOS"."NEXTVAL",
	"ID_ENCUENTRO" NUMBER,
	"PRESUPUESTO_TOTAL" NUMBER(15,2) DEFAULT 0
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECORDATORIOS
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS"
   (	"ID_RECORDATORIO" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_RECORDATORIOS"."NEXTVAL",
	"ID_USUARIO" NUMBER,
	"ID_ENCUENTRO" NUMBER,
	"FECHA_NOTIFICACION" TIMESTAMP (6),
	"ENVIADO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RELACIONES_AMISTADES
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES"
   (	"ID_RELACION_AMISTAD" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_RELACIONES_AMISTADES"."NEXTVAL",
	"ID_USUARIO" NUMBER,
	"FECHA_SOLICITUD_AMISTAD" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"FECHA_ACEPTACION_AMISTAD" TIMESTAMP (6) DEFAULT NULL,
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'pendiente'
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOLICITUDES_AMISTAD
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD"
   (	"ID_SOLICITUD_AMISTAD" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_SOLICITUDES_AMISTAD"."NEXTVAL",
	"ID_RELACION_AMISTAD" NUMBER,
	"USUARIO_DESTINO" NUMBER,
	"USUARIO_ORIGEN" NUMBER
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."USUARIOS"
   (	"ID_USUARIO" NUMBER DEFAULT "ENCUENTROS_ADMIN"."SEQ_USUARIOS"."NEXTVAL",
	"NOMBRE" VARCHAR2(100 BYTE),
	"APELLIDO" VARCHAR2(100 BYTE),
	"EMAIL" VARCHAR2(150 BYTE),
	"CONTRASENA" VARCHAR2(250 BYTE),
	"IMAGEN_PERFIL" VARCHAR2(255 BYTE),
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table migrations
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."migrations"
   (	"id" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE ,
	"timestamp" NUMBER,
	"name" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table typeorm_metadata
--------------------------------------------------------

CREATE TABLE "ENCUENTROS_ADMIN"."typeorm_metadata"
   (	"type" VARCHAR2(255 BYTE),
	"database" VARCHAR2(255 BYTE),
	"schema" VARCHAR2(255 BYTE),
	"table" VARCHAR2(255 BYTE),
	"name" VARCHAR2(255 BYTE),
	"value" CLOB
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"
 LOB ("value") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for View VISTAPARTICIPANTESAPORTES
--------------------------------------------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ENCUENTROS_ADMIN"."VISTAPARTICIPANTESAPORTES" ("ID_ENCUENTRO", "NOMBRE_ENCUENTRO", "ID_USUARIO", "NOMBRE_USUARIO", "APELLIDO_USUARIO", "ROL", "TOTAL_APORTES") AS
  SELECT
    p.id_encuentro,
    e.titulo AS nombre_encuentro,
    p.id_usuario,
    u.nombre AS nombre_usuario,
    u.apellido AS apellido_usuario,
    p.rol,
    NVL(SUM(a.monto),0) AS total_aportes
FROM Participantes_Encuentro p
JOIN Usuarios u ON p.id_usuario = u.id_usuario
JOIN Encuentros e ON p.id_encuentro = e.id_encuentro
LEFT JOIN Aportes a ON p.id_usuario = a.id_usuario
                     AND p.id_encuentro = a.id_encuentro
GROUP BY
    p.id_encuentro, e.titulo, p.id_usuario, u.nombre, u.apellido, p.rol
;
--------------------------------------------------------
--  DDL for View VISTAPRESUPUESTOSGASTOS
--------------------------------------------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ENCUENTROS_ADMIN"."VISTAPRESUPUESTOSGASTOS" ("ID_ENCUENTRO", "NOMBRE_ENCUENTRO", "PRESUPUESTO_TOTAL", "TOTAL_GASTOS", "SALDO") AS
  SELECT
    e.id_encuentro,
    e.titulo AS nombre_encuentro,
    p.presupuesto_total,
    NVL(SUM(g.monto),0) AS total_gastos,
    (p.presupuesto_total - NVL(SUM(g.monto),0)) AS saldo
FROM Encuentros e
JOIN Presupuestos p ON e.id_encuentro = p.id_encuentro
LEFT JOIN Gastos g ON e.id_encuentro = g.id_encuentro
GROUP BY e.id_encuentro, e.titulo, p.presupuesto_total
;
--------------------------------------------------------
--  DDL for View V_ENCUENTRO_RESUMEN
--------------------------------------------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ENCUENTROS_ADMIN"."V_ENCUENTRO_RESUMEN" ("ID_ENCUENTRO", "TITULO", "LUGAR", "FECHA", "ID_PRESUPUESTO", "PRESUPUESTO_TOTAL", "ID_BOLSILLO", "NOMBRE_BOLSILLO", "SALDO_BOLSILLO", "CANT_PARTICIPANTES") AS
  SELECT
    e.id_encuentro,
    e.titulo,
    e.lugar,
    e.fecha,
    NVL(p.id_presupuesto, NULL) AS id_presupuesto,
    NVL(p.presupuesto_total, 0) AS presupuesto_total,
    NVL(b.id_bolsillo, NULL) AS id_bolsillo,
    NVL(b.nombre, 'SIN_BOLSILLO') AS nombre_bolsillo,
    NVL(b.saldo_actual, 0) AS saldo_bolsillo,
    NVL(pe.cant_participantes, 0) AS cant_participantes
FROM Encuentros e
LEFT JOIN Presupuestos p ON e.id_encuentro = p.id_encuentro         -- JOIN 1
LEFT JOIN Bolsillos b   ON e.id_encuentro = b.id_encuentro           -- JOIN 2
LEFT JOIN (
    SELECT id_encuentro, COUNT(*) AS cant_participantes
    FROM Participantes_Encuentro
    GROUP BY id_encuentro
) pe ON e.id_encuentro = pe.id_encuentro                            -- JOIN 3 (a subconsulta)
;
--------------------------------------------------------
--  DDL for View V_PARTICIPANTES_ENCUENTRO
--------------------------------------------------------

CREATE OR REPLACE FORCE EDITIONABLE VIEW "ENCUENTROS_ADMIN"."V_PARTICIPANTES_ENCUENTRO" ("ID_ENCUENTRO", "TITULO_ENCUENTRO", "FECHA", "ID_USUARIO", "NOMBRE_COMPLETO", "ROL") AS
  SELECT
    e.id_encuentro,
    e.titulo AS titulo_encuentro,
    e.fecha,
    u.id_usuario,
    u.nombre || ' ' || u.apellido AS nombre_completo,
    p.rol
FROM Participantes_Encuentro p
JOIN Usuarios u ON p.id_usuario = u.id_usuario
JOIN Encuentros e ON p.id_encuentro = e.id_encuentro
;

REM INSERTING into ENCUENTROS_ADMIN.AMISTADES SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.APORTES SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.BOLSILLOS SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.ENCUENTROS SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.GASTOS SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.ITEMS_PRESUPUESTO SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.MENSAJES SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.PARTICIPANTES_ENCUENTRO
SET
    DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.PRESUPUESTOS SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.RECORDATORIOS SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.RELACIONES_AMISTADES
SET
    DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.SOLICITUDES_AMISTAD
SET
    DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.USUARIOS SET DEFINE OFF;

Insert into
    ENCUENTROS_ADMIN.USUARIOS (
        ID_USUARIO,
        NOMBRE,
        APELLIDO,
        EMAIL,
        CONTRASENA,
        IMAGEN_PERFIL,
        FECHA_REGISTRO
    )
values (
        21,
        'Tomi',
        'Ramirez',
        'tomi@gmail.com',
        '$2b$10$3Se841fyUDf.uD4tugBnVOQA1infMxWCyBCsBbjdtAipcQ6HxfuQW',
        null,
        to_timestamp (
            '06-NOV-25 02.08.06.094000000 AM',
            'DD-MON-RR HH.MI.SSXFF AM'
        )
    );

REM INSERTING into ENCUENTROS_ADMIN."migrations" SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN."typeorm_metadata"
SET DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.VISTAPARTICIPANTESAPORTES
SET
    DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.VISTAPRESUPUESTOSGASTOS
SET
    DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.V_ENCUENTRO_RESUMEN
SET
    DEFINE OFF;

REM INSERTING into ENCUENTROS_ADMIN.V_PARTICIPANTES_ENCUENTRO
SET
    DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IDX_AMISTAD_RELACION
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_AMISTAD_RELACION" ON "ENCUENTROS_ADMIN"."AMISTADES" ("ID_RELACION_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AMISTAD_USUARIO1
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_AMISTAD_USUARIO1" ON "ENCUENTROS_ADMIN"."AMISTADES" ("USUARIO1")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AMISTAD_USUARIO2
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_AMISTAD_USUARIO2" ON "ENCUENTROS_ADMIN"."AMISTADES" ("USUARIO2")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APORTES_BOLSILLO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_APORTES_BOLSILLO" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_BOLSILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APORTES_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_APORTES_ENCUENTRO" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APORTES_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_APORTES_USUARIO" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_BOLSILLOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_BOLSILLOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_BOLSILLOS_PRESUPUESTO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_BOLSILLOS_PRESUPUESTO" ON "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_PRESUPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ENCUENTROS_CREADOR
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ENCUENTROS_CREADOR" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_CREADOR")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ENCUENTROS_ESTADO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ENCUENTROS_ESTADO" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("ESTADO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ENCUENTROS_FECHA
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ENCUENTROS_FECHA" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("FECHA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GASTOS_BOLSILLO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_GASTOS_BOLSILLO" ON "ENCUENTROS_ADMIN"."GASTOS" ("ID_BOLSILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GASTOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_GASTOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."GASTOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ITEM_PRESUPUESTO_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ITEM_PRESUPUESTO_ENCUENTRO" ON "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ITEM_PRESUPUESTO_PRESUPUESTO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ITEM_PRESUPUESTO_PRESUPUESTO" ON "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ("ID_PRESUPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_MENSAJES_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_MENSAJES_ENCUENTRO" ON "ENCUENTROS_ADMIN"."MENSAJES" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_MENSAJES_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_MENSAJES_USUARIO" ON "ENCUENTROS_ADMIN"."MENSAJES" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PARTICIPANTES_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_PARTICIPANTES_ENCUENTRO" ON "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PARTICIPANTES_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_PARTICIPANTES_USUARIO" ON "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PRESUPUESTOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_PRESUPUESTOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."PRESUPUESTOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RECORDATORIOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_RECORDATORIOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RECORDATORIOS_ENVIADO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_RECORDATORIOS_ENVIADO" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ENVIADO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RECORDATORIOS_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_RECORDATORIOS_USUARIO" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_REL_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_REL_USUARIO" ON "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SOL_RELACION
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_SOL_RELACION" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("ID_RELACION_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SOL_USUARIO_DESTINO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_SOL_USUARIO_DESTINO" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("USUARIO_DESTINO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SOL_USUARIO_ORIGEN
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_SOL_USUARIO_ORIGEN" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("USUARIO_ORIGEN")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_8c82d7f526340ab734260ea46be
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."PK_8c82d7f526340ab734260ea46be" ON "ENCUENTROS_ADMIN"."migrations" ("id")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008494
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008494" ON "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008495
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008495" ON "ENCUENTROS_ADMIN"."USUARIOS" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008499
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008499" ON "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ("ID_RELACION_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008504
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008504" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("ID_SOLICITUD_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008511
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008511" ON "ENCUENTROS_ADMIN"."AMISTADES" ("ID_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008518
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008518" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008524
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008524" ON "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ("ID_PARTICIPACION")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008531
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008531" ON "ENCUENTROS_ADMIN"."MENSAJES" ("ID_MENSAJE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008539
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008539" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ID_RECORDATORIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008619
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008619" ON "ENCUENTROS_ADMIN"."PRESUPUESTOS" ("ID_PRESUPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008625
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008625" ON "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ("ID_ITEM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008631
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008631" ON "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_BOLSILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008639
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008639" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_APORTE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008648
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008648" ON "ENCUENTROS_ADMIN"."GASTOS" ("ID_GASTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000079348C00004$$
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_IL0000079348C00004$$" ON "ENCUENTROS_ADMIN"."ENCUENTROS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000079354C00004$$
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_IL0000079354C00004$$" ON "ENCUENTROS_ADMIN"."MENSAJES" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000080107C00006$$
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_IL0000080107C00006$$" ON "ENCUENTROS_ADMIN"."typeorm_metadata" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index IDX_AMISTAD_RELACION
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_AMISTAD_RELACION" ON "ENCUENTROS_ADMIN"."AMISTADES" ("ID_RELACION_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AMISTAD_USUARIO1
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_AMISTAD_USUARIO1" ON "ENCUENTROS_ADMIN"."AMISTADES" ("USUARIO1")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_AMISTAD_USUARIO2
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_AMISTAD_USUARIO2" ON "ENCUENTROS_ADMIN"."AMISTADES" ("USUARIO2")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008511
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008511" ON "ENCUENTROS_ADMIN"."AMISTADES" ("ID_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APORTES_BOLSILLO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_APORTES_BOLSILLO" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_BOLSILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APORTES_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_APORTES_ENCUENTRO" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APORTES_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_APORTES_USUARIO" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008639
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008639" ON "ENCUENTROS_ADMIN"."APORTES" ("ID_APORTE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_BOLSILLOS_PRESUPUESTO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_BOLSILLOS_PRESUPUESTO" ON "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_PRESUPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_BOLSILLOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_BOLSILLOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008631
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008631" ON "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_BOLSILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ENCUENTROS_CREADOR
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ENCUENTROS_CREADOR" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_CREADOR")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ENCUENTROS_FECHA
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ENCUENTROS_FECHA" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("FECHA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ENCUENTROS_ESTADO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ENCUENTROS_ESTADO" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("ESTADO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008518
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008518" ON "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GASTOS_BOLSILLO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_GASTOS_BOLSILLO" ON "ENCUENTROS_ADMIN"."GASTOS" ("ID_BOLSILLO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_GASTOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_GASTOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."GASTOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008648
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008648" ON "ENCUENTROS_ADMIN"."GASTOS" ("ID_GASTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ITEM_PRESUPUESTO_PRESUPUESTO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ITEM_PRESUPUESTO_PRESUPUESTO" ON "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ("ID_PRESUPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008625
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008625" ON "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ("ID_ITEM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_ITEM_PRESUPUESTO_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_ITEM_PRESUPUESTO_ENCUENTRO" ON "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_MENSAJES_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_MENSAJES_ENCUENTRO" ON "ENCUENTROS_ADMIN"."MENSAJES" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_MENSAJES_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_MENSAJES_USUARIO" ON "ENCUENTROS_ADMIN"."MENSAJES" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008531
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008531" ON "ENCUENTROS_ADMIN"."MENSAJES" ("ID_MENSAJE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PARTICIPANTES_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_PARTICIPANTES_ENCUENTRO" ON "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PARTICIPANTES_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_PARTICIPANTES_USUARIO" ON "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008524
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008524" ON "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ("ID_PARTICIPACION")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008619
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008619" ON "ENCUENTROS_ADMIN"."PRESUPUESTOS" ("ID_PRESUPUESTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PRESUPUESTOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_PRESUPUESTOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."PRESUPUESTOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RECORDATORIOS_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_RECORDATORIOS_USUARIO" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RECORDATORIOS_ENCUENTRO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_RECORDATORIOS_ENCUENTRO" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ID_ENCUENTRO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RECORDATORIOS_ENVIADO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_RECORDATORIOS_ENVIADO" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ENVIADO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008539
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008539" ON "ENCUENTROS_ADMIN"."RECORDATORIOS" ("ID_RECORDATORIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_REL_USUARIO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_REL_USUARIO" ON "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008499
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008499" ON "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ("ID_RELACION_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SOL_RELACION
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_SOL_RELACION" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("ID_RELACION_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SOL_USUARIO_DESTINO
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_SOL_USUARIO_DESTINO" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("USUARIO_DESTINO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_SOL_USUARIO_ORIGEN
--------------------------------------------------------

CREATE INDEX "ENCUENTROS_ADMIN"."IDX_SOL_USUARIO_ORIGEN" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("USUARIO_ORIGEN")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008504
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008504" ON "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ("ID_SOLICITUD_AMISTAD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008494
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008494" ON "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008495
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."SYS_C008495" ON "ENCUENTROS_ADMIN"."USUARIOS" ("EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_8c82d7f526340ab734260ea46be
--------------------------------------------------------

CREATE UNIQUE INDEX "ENCUENTROS_ADMIN"."PK_8c82d7f526340ab734260ea46be" ON "ENCUENTROS_ADMIN"."migrations" ("id")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure ACEPTAR_SOLICITUD_AMISTAD
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."ACEPTAR_SOLICITUD_AMISTAD" (
    p_id_relacion_amistad IN NUMBER,   -- ID de la relación de amistad
    p_usuario1 IN NUMBER               -- Usuario que intenta aceptar la solicitud
) AS
    v_usuario_origen   NUMBER;

v_usuario_destino NUMBER;

v_estado VARCHAR2 (20);

BEGIN
    -- 1️⃣ Obtener datos de la relación: quién envió la solicitud y su estado
    SELECT id_usuario, estado
    INTO v_usuario_origen, v_estado
    FROM RELACIONES_AMISTADES
    WHERE id_relacion_amistad = p_id_relacion_amistad;

    -- 2️⃣ Si el estado ya está en 'aceptada', lanzar error
    IF v_estado = 'aceptada' THEN
        RAISE_APPLICATION_ERROR(-20002, 'La solicitud de amistad ya está aceptada.');
    END IF;

    -- 3️⃣ Obtener el usuario destino (a quién se le envió la solicitud)
    SELECT usuario_destino
    INTO v_usuario_destino
    FROM SOLICITUDES_AMISTAD
    WHERE id_relacion_amistad = p_id_relacion_amistad;

    -- 4️⃣ Validar que el usuario que intenta aceptar es efectivamente el destinatario
    IF p_usuario1 != v_usuario_destino THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'El usuario que intenta aceptar no es el destinatario de la solicitud de amistad.'
        );
    END IF;

    -- 5️⃣ Actualizar el estado de la relación a 'aceptada' y registrar la fecha
    UPDATE RELACIONES_AMISTADES
    SET estado = 'aceptada',
        fecha_aceptacion_amistad = CURRENT_TIMESTAMP
    WHERE id_relacion_amistad = p_id_relacion_amistad;

    -- 6️⃣ Insertar en la tabla AMISTADES
    INSERT INTO AMISTADES (
        id_relacion_amistad,
        usuario1,
        usuario2,
        fecha_amistad
    ) VALUES (
        p_id_relacion_amistad,
        v_usuario_origen,   -- quien envió la solicitud
        v_usuario_destino,  -- quien la aceptó
        CURRENT_TIMESTAMP
    );

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se encontró la solicitud o la relación de amistad.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END aceptar_solicitud_amistad;
;

/
--------------------------------------------------------
--  DDL for Procedure AGREGAR_APORTE
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."AGREGAR_APORTE" (
    p_id_bolsillo IN NUMBER,
    p_id_encuentro IN NUMBER,
    p_id_usuario IN NUMBER,
    p_monto IN NUMBER
) AS
    v_id_encuentro_bolsillo NUMBER;

v_count_participante NUMBER;

BEGIN
    -- 1️⃣ Verificar que el bolsillo pertenezca al encuentro indicado
    SELECT id_encuentro
    INTO v_id_encuentro_bolsillo
    FROM Bolsillos
    WHERE id_bolsillo = p_id_bolsillo;

    IF v_id_encuentro_bolsillo != p_id_encuentro THEN
        RAISE_APPLICATION_ERROR(-20001, 'El bolsillo no corresponde al encuentro indicado.');
    END IF;

    -- 2️⃣ Verificar que el usuario pertenezca al encuentro
    SELECT COUNT(*)
    INTO v_count_participante
    FROM Participantes_Encuentro
    WHERE id_usuario = p_id_usuario
      AND id_encuentro = p_id_encuentro;

    IF v_count_participante = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El usuario no pertenece al encuentro indicado.');
    END IF;

    -- 3️⃣ Insertar el aporte
    INSERT INTO Aportes (
        id_aporte,
        id_bolsillo,
        id_encuentro,
        id_usuario,
        monto,
        fecha_aporte
    ) VALUES (
        seq_aportes.NEXTVAL,
        p_id_bolsillo,
        p_id_encuentro,
        p_id_usuario,
        p_monto,
        CURRENT_TIMESTAMP
    );

    -- 4️⃣ Actualizar el saldo del bolsillo
    UPDATE Bolsillos
    SET saldo_actual = saldo_actual + p_monto
    WHERE id_bolsillo = p_id_bolsillo;

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'El bolsillo especificado no existe.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END agregar_aporte;
;

/
--------------------------------------------------------
--  DDL for Procedure AGREGAR_GASTO
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."AGREGAR_GASTO" (
    p_id_bolsillo IN NUMBER,
    p_id_encuentro IN NUMBER,
    p_nombre_item IN VARCHAR2,
    p_monto IN NUMBER
) AS
    v_id_encuentro_bolsillo NUMBER;

v_saldo_actual NUMBER (15, 2);

BEGIN
    -- 1️⃣ Verificar que el bolsillo exista y obtener su encuentro
    SELECT id_encuentro, saldo_actual
    INTO v_id_encuentro_bolsillo, v_saldo_actual
    FROM Bolsillos
    WHERE id_bolsillo = p_id_bolsillo;

    -- 2️⃣ Validar que el bolsillo pertenezca al encuentro indicado
    IF v_id_encuentro_bolsillo != p_id_encuentro THEN
        RAISE_APPLICATION_ERROR(-20001, 'El bolsillo no corresponde al encuentro indicado.');
    END IF;

    -- 3️⃣ Validar que haya suficiente saldo
    IF p_monto > v_saldo_actual THEN
        RAISE_APPLICATION_ERROR(-20002, 'Saldo insuficiente en el bolsillo para realizar el gasto.');
    END IF;

    -- 4️⃣ Insertar el gasto
    INSERT INTO Gastos (
        id_gasto,
        id_bolsillo,
        id_encuentro,
        nombre_item,
        monto,
        fecha_gasto
    ) VALUES (
        seq_gastos.NEXTVAL,
        p_id_bolsillo,
        p_id_encuentro,
        p_nombre_item,
        p_monto,
        CURRENT_TIMESTAMP
    );

    -- 5️⃣ Actualizar saldo del bolsillo
    UPDATE Bolsillos
    SET saldo_actual = saldo_actual - p_monto
    WHERE id_bolsillo = p_id_bolsillo;

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'El bolsillo especificado no existe.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END agregar_gasto;
;

/
--------------------------------------------------------
--  DDL for Procedure AGREGAR_ITEM_PRESUPUESTO
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."AGREGAR_ITEM_PRESUPUESTO" (
    p_id_presupuesto IN NUMBER,
    p_id_encuentro   IN NUMBER,
    p_nombre_item    IN VARCHAR2,
    p_monto_item     IN NUMBER
) AS
    v_id_encuentro_presupuesto  NUMBER;
BEGIN
    -- 1️⃣ Verificar que el presupuesto exista y obtener su id_encuentro
    SELECT id_encuentro
    INTO v_id_encuentro_presupuesto
    FROM Presupuestos
    WHERE id_presupuesto = p_id_presupuesto;

    -- 2️⃣ Validar que el id_encuentro proporcionado corresponda al del presupuesto
    IF v_id_encuentro_presupuesto != p_id_encuentro THEN
        RAISE_APPLICATION_ERROR(-20001, 'El id_encuentro no corresponde al presupuesto indicado.');
    END IF;

    -- 3️⃣ Insertar el nuevo ítem en la tabla Items_Presupuesto
    INSERT INTO Items_Presupuesto (
        id_item,
        id_presupuesto,
        id_encuentro,
        nombre_item,
        monto_item
    ) VALUES (
        seq_items_presupuesto.NEXTVAL,
        p_id_presupuesto,
        p_id_encuentro,
        p_nombre_item,
        p_monto_item
    );

    -- 4️⃣ Actualizar el total del presupuesto
    UPDATE Presupuestos
    SET presupuesto_total = presupuesto_total + p_monto_item
    WHERE id_presupuesto = p_id_presupuesto;

    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'No existe el presupuesto especificado.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END agregar_item_presupuesto;
;

/
--------------------------------------------------------
--  DDL for Procedure AGREGAR_PARTICIPANTE_ENCUENTRO
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."AGREGAR_PARTICIPANTE_ENCUENTRO" (
    p_id_encuentro IN NUMBER,
    p_id_usuario   IN NUMBER,
    p_rol          IN VARCHAR2 DEFAULT 'participante'
) AS
    v_id_creador          NUMBER;

v_count_participante NUMBER;

v_count_amistad NUMBER;

BEGIN
    -- 1️⃣ Verificar si el rol no permitido
    IF LOWER(p_rol) = 'organizador' THEN
        RAISE_APPLICATION_ERROR(-20000, 'No se puede agregar un participante con el rol de organizador.');
    END IF;

    -- 2️⃣ Verificar si el usuario ya está agregado en el encuentro
    SELECT COUNT(*)
    INTO v_count_participante
    FROM Participantes_Encuentro
    WHERE id_encuentro = p_id_encuentro
      AND id_usuario = p_id_usuario;

    IF v_count_participante > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El usuario ya está agregado en este encuentro.');
    END IF;

    -- 3️⃣ Obtener el ID del creador del encuentro
    SELECT id_creador
    INTO v_id_creador
    FROM Encuentros
    WHERE id_encuentro = p_id_encuentro;

    -- 4️⃣ Verificar si el usuario es amigo del creador (en ambas direcciones)
    SELECT COUNT(*)
    INTO v_count_amistad
    FROM AMISTADES
    WHERE (usuario1 = v_id_creador AND usuario2 = p_id_usuario)
       OR (usuario2 = v_id_creador AND usuario1 = p_id_usuario);

    IF v_count_amistad = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El usuario no es amigo del creador.');
    END IF;

    -- 5️⃣ Insertar el nuevo participante
    INSERT INTO Participantes_Encuentro (
        id_encuentro,
        id_usuario,
        rol
    ) VALUES (
        p_id_encuentro,
        p_id_usuario,
        p_rol
    );

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'El encuentro especificado no existe.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END agregar_participante_encuentro;
;

/
--------------------------------------------------------
--  DDL for Procedure CREAR_ENCUENTRO
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."CREAR_ENCUENTRO" (
    p_id_creador   IN NUMBER,
    p_titulo       IN VARCHAR2,
    p_descripcion  IN CLOB,
    p_lugar        IN VARCHAR2,
    p_fecha        IN DATE
) AS
    v_id_encuentro   NUMBER;

v_id_presupuesto NUMBER;

BEGIN
    -- 1️⃣ Crear el encuentro
    INSERT INTO Encuentros (
        id_creador,
        titulo,
        descripcion,
        lugar,
        fecha
    ) VALUES (
        p_id_creador,
        p_titulo,
        p_descripcion,
        p_lugar,
        p_fecha
    )
    RETURNING id_encuentro INTO v_id_encuentro;

    -- 2️⃣ Registrar al creador como organizador
    INSERT INTO Participantes_Encuentro (
        id_encuentro,
        id_usuario,
        rol
    ) VALUES (
        v_id_encuentro,
        p_id_creador,
        'organizador'
    );

    -- 3️⃣ Crear el presupuesto base del encuentro
    INSERT INTO Presupuestos (
        id_encuentro,
        presupuesto_total
    ) VALUES (
        v_id_encuentro,
        0
    )
    RETURNING id_presupuesto INTO v_id_presupuesto;

    -- 4️⃣ Crear el bolsillo asociado al presupuesto
    INSERT INTO Bolsillos (
        id_presupuesto,
        id_encuentro,
        nombre,
        saldo_actual
    ) VALUES (
        v_id_presupuesto,
        v_id_encuentro,
        'Bolsillo principal',
        0
    );

    COMMIT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se encontró información al crear el encuentro.');
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20002, 'El encuentro ya existe.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20003, 'Error inesperado al crear el encuentro: ' || SQLERRM);
END crear_encuentro;
;

/
--------------------------------------------------------
--  DDL for Procedure CREAR_SOLICITUD_AMISTAD
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."CREAR_SOLICITUD_AMISTAD" (
    p_usuario_origen  IN NUMBER,
    p_usuario_destino IN NUMBER
)
AS
    v_id_relacion_amistad NUMBER;

v_usuario_origen NUMBER;

v_count_cruzada NUMBER;

v_count_directa NUMBER;

BEGIN
    -- 1️⃣ Verificar si el usuario destino ya le envió una solicitud al origen (solicitud cruzada)
    SELECT COUNT(*)
      INTO v_count_cruzada
      FROM SOLICITUDES_AMISTAD sa
      JOIN RELACIONES_AMISTADES ra
        ON sa.id_relacion_amistad = ra.id_relacion_amistad
     WHERE ra.id_usuario = p_usuario_destino   -- el otro fue el origen
       AND sa.usuario_destino = p_usuario_origen
       AND ra.estado = 'pendiente';

    IF v_count_cruzada > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'El usuario al que le va a enviar una solicitud ya le ha enviado una a usted.'
        );
    END IF;

    -- 2️⃣ Verificar si ya existe una solicitud pendiente en el mismo sentido
    SELECT COUNT(*)
      INTO v_count_directa
      FROM SOLICITUDES_AMISTAD sa
      JOIN RELACIONES_AMISTADES ra
        ON sa.id_relacion_amistad = ra.id_relacion_amistad
     WHERE ra.id_usuario = p_usuario_origen
       AND sa.usuario_destino = p_usuario_destino
       AND ra.estado = 'pendiente';

    IF v_count_directa > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'Ya le ha enviado una solicitud de amistad a este usuario.'
        );
    END IF;

    -- 3️⃣ Insertar registro en RELACIONES_AMISTADES
    INSERT INTO RELACIONES_AMISTADES (
        id_usuario,
        fecha_solicitud_amistad,
        estado
    ) VALUES (
        p_usuario_origen,
        CURRENT_TIMESTAMP,
        'pendiente'
    )
    RETURNING id_relacion_amistad INTO v_id_relacion_amistad;

    -- 4️⃣ Obtener el id_usuario (usuario_origen) desde la tabla RELACIONES_AMISTADES recién creada
    SELECT id_usuario
      INTO v_usuario_origen
      FROM RELACIONES_AMISTADES
     WHERE id_relacion_amistad = v_id_relacion_amistad;

    -- 5️⃣ Insertar el registro en SOLICITUDES_AMISTAD
    INSERT INTO SOLICITUDES_AMISTAD (
        id_relacion_amistad,
        usuario_destino,
        usuario_origen
    ) VALUES (
        v_id_relacion_amistad,
        p_usuario_destino,
        v_usuario_origen
    );

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Error al crear la solicitud de amistad: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure ESTADISTICAS_EVENTOS_FINANCIEROS
--------------------------------------------------------
set define off;

CREATE OR REPLACE EDITIONABLE PROCEDURE "ENCUENTROS_ADMIN"."ESTADISTICAS_EVENTOS_FINANCIEROS" IS
    CURSOR c_eventos IS
        SELECT
            e.id_encuentro,
            e.titulo,
            e.estado,
            NVL(p.presupuesto_total, 0) AS presupuesto_total
        FROM Encuentros e
        LEFT JOIN Presupuestos p ON e.id_encuentro = p.id_encuentro;

v_id_encuentro NUMBER;

v_titulo VARCHAR2 (200);

v_estado VARCHAR2 (20);

v_presupuesto_total NUMBER (15, 2);

v_gastos_totales NUMBER (15, 2);

v_balance NUMBER (15, 2);

v_porcentaje NUMBER (5, 2);

BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE(' ESTADÍSTICAS FINANCIERAS DE ENCUENTROS ');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('ID | TÍTULO | ESTADO | PRESUPUESTO | GASTOS | BALANCE | % EJEC');

    FOR r_evento IN c_eventos LOOP
        v_id_encuentro := r_evento.id_encuentro;
        v_titulo := r_evento.titulo;
        v_estado := r_evento.estado;
        v_presupuesto_total := NVL(r_evento.presupuesto_total, 0);

        -- Calcular gastos totales del encuentro
        SELECT NVL(SUM(g.monto), 0)
        INTO v_gastos_totales
        FROM Gastos g
        WHERE g.id_encuentro = v_id_encuentro;

        -- Calcular balance
        v_balance := v_presupuesto_total - v_gastos_totales;

        -- Calcular porcentaje ejecutado
        IF v_presupuesto_total > 0 THEN
            v_porcentaje := (v_gastos_totales / v_presupuesto_total) * 100;
        ELSE
            v_porcentaje := 0;
        END IF;

        DBMS_OUTPUT.PUT_LINE(
            LPAD(v_id_encuentro, 3) || ' | ' ||
            RPAD(SUBSTR(v_titulo, 1, 20), 20) || ' | ' ||
            RPAD(v_estado, 10) || ' | ' ||
            LPAD(TO_CHAR(v_presupuesto_total, '999,999,999.99'), 15) || ' | ' ||
            LPAD(TO_CHAR(v_gastos_totales, '999,999,999.99'), 12) || ' | ' ||
            LPAD(TO_CHAR(v_balance, '999,999,999.99'), 12) || ' | ' ||
            LPAD(TO_CHAR(v_porcentaje, '90.00') || '%', 8)
        );
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------------');
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20010, 'Error al generar las estadísticas: ' || SQLERRM);
END estadisticas_eventos_financieros;
;

/
--------------------------------------------------------
--  DDL for Package PKG_CENTRAL
--------------------------------------------------------

CREATE OR REPLACE EDITIONABLE PACKAGE "ENCUENTROS_ADMIN"."PKG_CENTRAL" AS

    -- Crear un nuevo encuentro con todo lo asociado
    PROCEDURE crear_encuentro_central(
        p_id_creador IN NUMBER,
        p_titulo IN VARCHAR2,
        p_descripcion IN CLOB,
        p_lugar IN VARCHAR2,
        p_fecha IN DATE
    );

    -- Agregar un ítem al presupuesto
    PROCEDURE agregar_item_presupuesto_central(
        p_id_presupuesto IN NUMBER,
        p_id_encuentro IN NUMBER,
        p_nombre_item IN VARCHAR2,
        p_monto_item IN NUMBER
    );

    -- Registrar un aporte
    PROCEDURE agregar_aporte_central(
        p_id_bolsillo IN NUMBER,
        p_id_encuentro IN NUMBER,
        p_id_usuario IN NUMBER,
        p_monto IN NUMBER
    );

    -- Registrar un gasto
    PROCEDURE agregar_gasto_central(
        p_id_bolsillo IN NUMBER,
        p_id_encuentro IN NUMBER,
        p_nombre_item IN VARCHAR2,
        p_monto IN NUMBER
    );

END PKG_CENTRAL;
;

/
--------------------------------------------------------
--  DDL for Package Body PKG_CENTRAL
--------------------------------------------------------

CREATE OR REPLACE EDITIONABLE PACKAGE BODY "ENCUENTROS_ADMIN"."PKG_CENTRAL" AS

    -- ===============================
    -- CREAR ENCUENTRO CENTRAL
    -- ===============================
    PROCEDURE crear_encuentro_central(
        p_id_creador IN NUMBER,
        p_titulo IN VARCHAR2,
        p_descripcion IN CLOB,
        p_lugar IN VARCHAR2,
        p_fecha IN DATE
    ) IS
    BEGIN
        -- Llama al procedimiento existente que maneja todo el flujo de creación de encuentros
        crear_encuentro(
            p_id_creador => p_id_creador,
            p_titulo => p_titulo,
            p_descripcion => p_descripcion,
            p_lugar => p_lugar,
            p_fecha => p_fecha
        );
    END crear_encuentro_central;

    -- ===============================
    -- AGREGAR ITEM PRESUPUESTO
    -- ===============================
    PROCEDURE agregar_item_presupuesto_central(
        p_id_presupuesto IN NUMBER,
        p_id_encuentro IN NUMBER,
        p_nombre_item IN VARCHAR2,
        p_monto_item IN NUMBER
    ) IS
    BEGIN
        -- Llama al procedimiento existente
        agregar_item_presupuesto(
            p_id_presupuesto => p_id_presupuesto,
            p_id_encuentro => p_id_encuentro,
            p_nombre_item => p_nombre_item,
            p_monto_item => p_monto_item
        );
    END agregar_item_presupuesto_central;

    -- ===============================
    -- AGREGAR APORTE
    -- ===============================
    PROCEDURE agregar_aporte_central(
        p_id_bolsillo IN NUMBER,
        p_id_encuentro IN NUMBER,
        p_id_usuario IN NUMBER,
        p_monto IN NUMBER
    ) IS
    BEGIN
        -- Llama al procedimiento existente
        agregar_aporte(
            p_id_bolsillo => p_id_bolsillo,
            p_id_encuentro => p_id_encuentro,
            p_id_usuario => p_id_usuario,
            p_monto => p_monto
        );
    END agregar_aporte_central;

    -- ===============================
    -- AGREGAR GASTO
    -- ===============================
    PROCEDURE agregar_gasto_central(
        p_id_bolsillo IN NUMBER,
        p_id_encuentro IN NUMBER,
        p_nombre_item IN VARCHAR2,
        p_monto IN NUMBER
    ) IS
    BEGIN
        -- Llama al procedimiento existente
        agregar_gasto(
            p_id_bolsillo => p_id_bolsillo,
            p_id_encuentro => p_id_encuentro,
            p_nombre_item => p_nombre_item,
            p_monto => p_monto
        );
    END agregar_gasto_central;

END PKG_CENTRAL;
;

/
--------------------------------------------------------
--  Constraints for Table AMISTADES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" MODIFY ("ID_RELACION_AMISTAD" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" MODIFY ("USUARIO1" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" MODIFY ("USUARIO2" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" MODIFY ("FECHA_AMISTAD" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" ADD PRIMARY KEY ("ID_AMISTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APORTES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" MODIFY ("ID_BOLSILLO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" MODIFY ("MONTO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" MODIFY ("FECHA_APORTE" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" ADD PRIMARY KEY ("ID_APORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOLSILLOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."BOLSILLOS" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."BOLSILLOS" MODIFY ("NOMBRE" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."BOLSILLOS" MODIFY ("SALDO_ACTUAL" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."BOLSILLOS" ADD PRIMARY KEY ("ID_BOLSILLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENCUENTROS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" MODIFY ("ID_CREADOR" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" MODIFY ("TITULO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" MODIFY ("FECHA" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" MODIFY ("FECHA_CREACION" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" ADD PRIMARY KEY ("ID_ENCUENTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" ADD CONSTRAINT "CHK_ESTADO_ENCUENTRO" CHECK (estado IN ('realizado', 'en proceso')) ENABLE;
--------------------------------------------------------
--  Constraints for Table GASTOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" MODIFY ("ID_BOLSILLO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" MODIFY ("NOMBRE_ITEM" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" MODIFY ("MONTO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" MODIFY ("FECHA_GASTO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" ADD PRIMARY KEY ("ID_GASTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ITEMS_PRESUPUESTO
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" MODIFY ("ID_PRESUPUESTO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" MODIFY ("NOMBRE_ITEM" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" MODIFY ("MONTO_ITEM" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ADD PRIMARY KEY ("ID_ITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENSAJES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" MODIFY ("MENSAJE" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" MODIFY ("FECHA_ENVIO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" ADD PRIMARY KEY ("ID_MENSAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTICIPANTES_ENCUENTRO
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" MODIFY ("ROL" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ADD CHECK (rol IN ('organizador','tesorero','participante')) ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ADD PRIMARY KEY ("ID_PARTICIPACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRESUPUESTOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."PRESUPUESTOS" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."PRESUPUESTOS" MODIFY ("PRESUPUESTO_TOTAL" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."PRESUPUESTOS" ADD PRIMARY KEY ("ID_PRESUPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RECORDATORIOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" MODIFY ("ID_ENCUENTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" MODIFY ("FECHA_NOTIFICACION" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" MODIFY ("ENVIADO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" ADD CHECK (enviado IN ('S', 'N')) ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" ADD PRIMARY KEY ("ID_RECORDATORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RELACIONES_AMISTADES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" MODIFY ("FECHA_SOLICITUD_AMISTAD" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ADD CHECK (estado IN ('pendiente', 'aceptada')) ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ADD PRIMARY KEY ("ID_RELACION_AMISTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOLICITUDES_AMISTAD
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" MODIFY ("ID_RELACION_AMISTAD" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" MODIFY ("USUARIO_DESTINO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" MODIFY ("USUARIO_ORIGEN" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ADD PRIMARY KEY ("ID_SOLICITUD_AMISTAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" MODIFY ("CONTRASENA" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."USUARIOS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table migrations
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."migrations" MODIFY ("id" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."migrations" MODIFY ("timestamp" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."migrations" MODIFY ("name" NOT NULL ENABLE);

ALTER TABLE "ENCUENTROS_ADMIN"."migrations" ADD CONSTRAINT "PK_8c82d7f526340ab734260ea46be" PRIMARY KEY ("id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table typeorm_metadata
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."typeorm_metadata" MODIFY ("type" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AMISTADES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" ADD CONSTRAINT "FK_AMISTAD_RELACION" FOREIGN KEY ("ID_RELACION_AMISTAD")
	  REFERENCES "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ("ID_RELACION_AMISTAD") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."AMISTADES" ADD CONSTRAINT "FK_AMISTAD_USUARIO1" FOREIGN KEY ("USUARIO1")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APORTES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" ADD CONSTRAINT "FK_APORTES_BOLSILLO" FOREIGN KEY ("ID_BOLSILLO")
	  REFERENCES "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_BOLSILLO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" ADD CONSTRAINT "FK_APORTES_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."APORTES" ADD CONSTRAINT "FK_APORTES_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOLSILLOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."BOLSILLOS" ADD CONSTRAINT "FK_BOLSILLOS_PRESUPUESTO" FOREIGN KEY ("ID_PRESUPUESTO")
	  REFERENCES "ENCUENTROS_ADMIN"."PRESUPUESTOS" ("ID_PRESUPUESTO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."BOLSILLOS" ADD CONSTRAINT "FK_BOLSILLOS_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENCUENTROS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."ENCUENTROS" ADD CONSTRAINT "FK_ENCUENTRO_CREADOR" FOREIGN KEY ("ID_CREADOR")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GASTOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" ADD CONSTRAINT "FK_GASTOS_BOLSILLO" FOREIGN KEY ("ID_BOLSILLO")
	  REFERENCES "ENCUENTROS_ADMIN"."BOLSILLOS" ("ID_BOLSILLO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."GASTOS" ADD CONSTRAINT "FK_GASTOS_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEMS_PRESUPUESTO
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ADD CONSTRAINT "FK_ITEMS_PRESUPUESTO_PRESUPUESTO" FOREIGN KEY ("ID_PRESUPUESTO")
	  REFERENCES "ENCUENTROS_ADMIN"."PRESUPUESTOS" ("ID_PRESUPUESTO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."ITEMS_PRESUPUESTO" ADD CONSTRAINT "FK_ITEMS_PRESUPUESTO_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENSAJES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" ADD CONSTRAINT "FK_MENSAJES_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."MENSAJES" ADD CONSTRAINT "FK_MENSAJES_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPANTES_ENCUENTRO
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ADD CONSTRAINT "FK_PARTICIPANTES_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."PARTICIPANTES_ENCUENTRO" ADD CONSTRAINT "FK_PARTICIPANTES_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESUPUESTOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."PRESUPUESTOS" ADD CONSTRAINT "FK_PRESUPUESTOS_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECORDATORIOS
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" ADD CONSTRAINT "FK_RECORDATORIOS_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."RECORDATORIOS" ADD CONSTRAINT "FK_RECORDATORIOS_ENCUENTRO" FOREIGN KEY ("ID_ENCUENTRO")
	  REFERENCES "ENCUENTROS_ADMIN"."ENCUENTROS" ("ID_ENCUENTRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RELACIONES_AMISTADES
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ADD CONSTRAINT "FK_REL_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOLICITUDES_AMISTAD
--------------------------------------------------------

ALTER TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ADD CONSTRAINT "FK_SOL_RELACION" FOREIGN KEY ("ID_RELACION_AMISTAD")
	  REFERENCES "ENCUENTROS_ADMIN"."RELACIONES_AMISTADES" ("ID_RELACION_AMISTAD") ENABLE;

ALTER TABLE "ENCUENTROS_ADMIN"."SOLICITUDES_AMISTAD" ADD CONSTRAINT "FK_SOL_USUARIO_DESTINO" FOREIGN KEY ("USUARIO_DESTINO")
	  REFERENCES "ENCUENTROS_ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
