sonar.projectKey=encuentros-front
sonar.projectName=Encuentros Frontend

sonar.sources=src/app
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/encuentros-front/lcov.info
sonar.typescript.lcov.reportPaths=coverage/encuentros-front/lcov.info
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_5cf11c9160cf6756b9c8914a98dec7a1f5e3b9b3