import { MigrationInterface, QueryRunner } from "typeorm";

export class FixUserTable1759115415625 implements MigrationInterface {
    name = 'FixUserTable1759115415625'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP COLUMN "ID_USUARIO"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD "ID_USUARIO" number GENERATED BY DEFAULT AS IDENTITY`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD CONSTRAINT "PK_a6943e83fd32713023fb7a3c017" PRIMARY KEY ("ID_USUARIO")`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP COLUMN "CONTRASENA"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD "CONTRASENA" varchar2(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP COLUMN "FECHA_REGISTRO"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD "FECHA_REGISTRO" date DEFAULT SYSDATE NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP COLUMN "FECHA_REGISTRO"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD "FECHA_REGISTRO" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP COLUMN "CONTRASENA"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD "CONTRASENA" varchar2(250) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP CONSTRAINT "PK_a6943e83fd32713023fb7a3c017"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" DROP COLUMN "ID_USUARIO"`);
        await queryRunner.query(`ALTER TABLE "USUARIOS" ADD "ID_USUARIO" number NOT NULL`);
    }

}
